name: cdm_ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  detect_builds:
    runs-on: ubuntu-latest
    outputs:
      checks: ${{ steps.detect_check_builds.outputs.checks }}
    steps:
      - id: detect_check_builds
        shell: pwsh
        run: |
          ./Detect-Changes.ps1

  build:
    runs-on: ubuntu-latest
    needs: detect_builds
    outputs:
      releases: ${{ steps.build.outputs.releases }}
    strategy:
      matrix:
        check: ${{ fromJson(needs.detect_builds.outputs.checks) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: 'build ${{ matrix.check }}'
        id: build
        shell: pwsh
        run: |
          $ErrorActionPreference = "stop"
          Set-Location ${{ matrix.check }}
          Write-Output "Building check: ${{ matrix.check }}"
          $buildName = "${{ matrix.check}}" -replace "/", "_"
          go build -o $buildName
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Build failed: ${{ matrix.check }}"
            exit 1
          }

          Write-Output "Build succeeded: ${{ matrix.check }}"
          exit 0
